name=SHT40_DS28E18
version=1.0.0
author=Daniel Sart
maintainer=Daniel Sart
sentence=Library for SHT40 sensor connected via DS28E18 1-Wire to I2C bridge.
paragraph=This library allows communication with SHT40 sensors through the DS28E18 1-Wire to I2C bridge, using the DS28E18_DS2482_Library.
category=Sensors
url=https://github.com/DanielSart/SHT40_DS28E18
architectures=*
depends=DS28E18_DS2482_Library, Adafruit DS248x
