[platformio]
description = SHT40_DS28E18 Library Examples
default_envs = pico
src_dir = example/SHT40_DS28E18_Single_Sensor

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    file://.
    https://github.com/DanielSart/DS28E18_DS2482_Library.git
    adafruit/Adafruit DS248x @ ^1.0.1

[env:pico]
platform = raspberrypi
board = pico

[env:esp32dev]
platform = espressif32
board = esp32dev
